apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: gateway-service
build:
  artifacts:
  - image: gateway-service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8/deployment.yaml    
